
# 日志配置
logging:
  level:
    com.example.com.example.node_compare: info
    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  1000MB
       # 设置总上传的文件大小
       max-request-size:  30000MB
       enabled: true
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8099